---
# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: false
check_commit_message: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: false
deploy_client_to_rubygems: false
deploy_daily_client_to_pypi: false
deploy_daily_client_to_rubygems: false
deploy_to_pypi: false
docs_test: false
plugin_app_label: installer
plugin_camel: Pulp_Installer
plugin_camel_short: Installer
plugin_caps: PULP_INSTALLER
plugin_caps_short: INSTALLER
plugin_dash: pulp-installer
plugin_dash_short: installer
plugin_name: pulp_installer
plugin_snake: pulp_installer
pulp_settings: null
pulpcore_branch: master
pydocstyle: false
pypi_username: null
stable_branch: null
test_bindings: false
test_performance: false
travis_notifications: null
